import type { Category, Supplier } from "@/lib/domain/types";
import { addDays, todayIso } from "@/lib/util";

/**
 * A supplier as written by hand: the commercial facts only. Screening dates and
 * B-BBEE certificates are derived once in `withCompliance` rather than typed
 * out twenty times, so every seeded supplier is screened on the same day.
 */
type SeedSupplier = Omit<
  Supplier,
  "id" | "sanctionsCheckedAt" | "sanctionsResult" | "bbbeeLevel" | "bbbeeExpiry"
>;

function supplier(
  name: string,
  country: string,
  city: string,
  categories: Category[],
  certifications: string[],
  performanceRating: number,
  qualityScore: number,
  onTimeRate: number,
  responseRate: number,
  financialHealth: Supplier["financialHealth"],
  yearsInBusiness: number,
  currency: Supplier["currency"],
  minOrderValue: number,
  notes: string,
): SeedSupplier {
  return {
    name,
    country,
    city,
    categories,
    certifications,
    performanceRating,
    qualityScore,
    onTimeRate,
    responseRate,
    financialHealth,
    yearsInBusiness,
    currency,
    minOrderValue,
    contactName: `${name.split(" ")[0]} Sales`,
    contactEmail: `sales@${name.toLowerCase().replace(/[^a-z]+/g, "")}.co.za`,
    notes,
  };
}

/**
 * Complete a hand-written supplier with its compliance position. The screening
 * is recent and clean for everyone, and the B-BBEE certificate is read out of
 * the certifications the supplier already claims to hold, so the risk agent
 * cannot disagree with the certificate list.
 */
export function withCompliance(seed: SeedSupplier): Omit<Supplier, "id"> {
  const isSouthAfrican = seed.country === "South Africa";
  let bbbeeLevel: number | null = null;
  for (const certification of seed.certifications) {
    const match = certification.match(/b-?bbee level (\d+)/i);
    if (match?.[1]) {
      bbbeeLevel = Number.parseInt(match[1], 10);
      break;
    }
  }

  return {
    ...seed,
    sanctionsCheckedAt: addDays(todayIso(), -20),
    sanctionsResult: "clear",
    bbbeeLevel: isSouthAfrican ? bbbeeLevel : null,
    bbbeeExpiry: isSouthAfrican && bbbeeLevel !== null ? addDays(todayIso(), 300) : null,
  };
}

export const SEED_SUPPLIERS: SeedSupplier[] = [
  // IT hardware
  supplier(
    "Kestrel IT Solutions",
    "South Africa",
    "Cape Town",
    ["it-hardware", "software"],
    ["ISO 9001", "B-BBEE Level 2", "Microsoft CSP"],
    4.6,
    94,
    97,
    92,
    "strong",
    14,
    "ZAR",
    2_500,
    "Reseller for Dell and Lenovo. Two local depots, next-day on stocked lines.",
  ),
  supplier(
    "Circuit Bridge",
    "South Africa",
    "Johannesburg",
    ["it-hardware"],
    ["ISO 9001", "B-BBEE Level 1"],
    4.1,
    87,
    88,
    74,
    "stable",
    7,
    "ZAR",
    5_000,
    "Direct importer. Cheapest on bulk laptops, weakest on warranty turnaround.",
  ),
  supplier(
    "Northwind Hardware",
    "Singapore",
    "Singapore",
    ["it-hardware", "logistics"],
    ["ISO 14001", "EcoVadis Gold"],
    4.4,
    96,
    94,
    68,
    "strong",
    22,
    "USD",
    10_000,
    "Manufactures storage and networking. Long lead times, no local stock.",
  ),
  supplier(
    "Cape Tech Trading",
    "South Africa",
    "Cape Town",
    ["it-hardware", "office-furniture", "facilities"],
    ["B-BBEE Level 3"],
    3.5,
    71,
    74,
    61,
    "watch",
    4,
    "ZAR",
    1_000,
    "Lowest headline price, frequently misses delivery windows.",
  ),

  // Software
  supplier(
    "Vellum Software Group",
    "South Africa",
    "Pretoria",
    ["software", "professional-services"],
    ["ISO 27001", "POPIA compliant", "B-BBEE Level 1"],
    4.5,
    93,
    95,
    90,
    "strong",
    11,
    "ZAR",
    0,
    "Local reseller with in-country support engineers and local invoicing.",
  ),
  supplier(
    "Openlane Cloud",
    "United Kingdom",
    "London",
    ["software"],
    ["ISO 27001", "SOC 2 Type II", "Cyber Essentials"],
    4.2,
    90,
    91,
    84,
    "strong",
    9,
    "GBP",
    0,
    "Direct vendor. No local presence, so support is in UK business hours.",
  ),

  // Office furniture
  supplier(
    "Ubuntu Office Systems",
    "South Africa",
    "Gauteng",
    ["office-furniture", "facilities"],
    ["ISO 9001", "B-BBEE Level 2", "FSC Chain of Custody"],
    4.4,
    92,
    93,
    89,
    "strong",
    18,
    "ZAR",
    3_000,
    "Installs in all major metros. Strong on ergonomic ranges.",
  ),
  supplier(
    "Silverbirch Furniture",
    "South Africa",
    "Durban",
    ["office-furniture"],
    ["B-BBEE Level 4", "FSC Chain of Custody"],
    3.8,
    78,
    81,
    76,
    "stable",
    6,
    "ZAR",
    1_500,
    "Workshop manufacturer. Custom joinery, longer lead times on bespoke items.",
  ),
  supplier(
    "Nordwerk Interiors",
    "Germany",
    "Leipzig",
    ["office-furniture"],
    ["FSC Chain of Custody", "ISO 14001", "Greenguard Gold"],
    4.7,
    97,
    89,
    63,
    "strong",
    41,
    "EUR",
    20_000,
    "Design-led European manufacturer. Premium pricing, exceptional build quality.",
  ),

  // Facilities
  supplier(
    "Ironwood Facilities Services",
    "South Africa",
    "Johannesburg",
    ["facilities", "professional-services"],
    ["ISO 9001", "B-BBEE Level 1", "OHSAS 18001"],
    4.3,
    89,
    91,
    87,
    "strong",
    16,
    "ZAR",
    5_000,
    "National maintenance and fit-out contractor.",
  ),
  supplier(
    "Greenline Sustainable",
    "South Africa",
    "Cape Town",
    ["facilities", "general"],
    ["ISO 14001", "B-BBEE Level 2"],
    4.0,
    88,
    86,
    85,
    "stable",
    8,
    "ZAR",
    2_000,
    "Specialises in energy and waste services. Good on sustainability reporting.",
  ),

  // Professional services
  supplier(
    "Moyo Advisory",
    "South Africa",
    "Cape Town",
    ["professional-services"],
    ["B-BBEE Level 1", "ISO 9001"],
    4.2,
    91,
    88,
    82,
    "strong",
    12,
    "ZAR",
    25_000,
    "Strategy and process consulting. Day-rate based, strong on scoping discipline.",
  ),
  supplier(
    "Halcyon Legal",
    "South Africa",
    "Pretoria",
    ["professional-services"],
    ["B-BBEE Level 2", "Legal Practice Council registered"],
    4.6,
    95,
    93,
    80,
    "strong",
    19,
    "ZAR",
    50_000,
    "Commercial legal. Expensive but the most reliable on contractual risk.",
  ),
  supplier(
    "Brightpath Training",
    "South Africa",
    "Johannesburg",
    ["professional-services", "marketing"],
    ["B-BBEE Level 1", "CPD accredited"],
    3.9,
    84,
    82,
    90,
    "stable",
    5,
    "ZAR",
    10_000,
    "Facilitated training and workshops. Very responsive, modest depth.",
  ),

  // Marketing
  supplier(
    "Signal & Co",
    "South Africa",
    "Johannesburg",
    ["marketing"],
    ["B-BBEE Level 2"],
    4.1,
    86,
    85,
    88,
    "stable",
    9,
    "ZAR",
    8_000,
    "Below-the-line media buying and campaign execution.",
  ),
  supplier(
    "Panorama Events",
    "South Africa",
    "Cape Town",
    ["marketing", "logistics", "facilities"],
    ["ISO 9001", "B-BBEE Level 3"],
    4.2,
    88,
    90,
    86,
    "strong",
    10,
    "ZAR",
    15_000,
    "Full service events production across SA, with regional partners.",
  ),

  // Lab equipment
  supplier(
    "Stellar Lab Solutions",
    "South Africa",
    "Johannesburg",
    ["lab-equipment"],
    ["ISO 9001", "ISO 13485", "B-BBEE Level 1"],
    4.5,
    95,
    93,
    79,
    "strong",
    13,
    "ZAR",
    20_000,
    "Calibrated analytical instruments with local service contracts.",
  ),
  supplier(
    "Meridian Instruments",
    "Germany",
    "Munich",
    ["lab-equipment", "it-hardware"],
    ["ISO 13485", "CE marked", "ISO 9001"],
    4.8,
    98,
    86,
    58,
    "strong",
    63,
    "EUR",
    30_000,
    "German precision manufacturer. Highest build quality, weakest lead times.",
  ),

  // Logistics
  supplier(
    "Freightline SA",
    "South Africa",
    "Johannesburg",
    ["logistics", "it-hardware"],
    ["ISO 9001", "B-BBEE Level 1", "ISO 14001"],
    4.3,
    90,
    95,
    91,
    "strong",
    20,
    "ZAR",
    3_000,
    "Asset-light freight and customs clearance across all major ports.",
  ),
  supplier(
    "Harbour Link",
    "South Africa",
    "Cape Town",
    ["logistics"],
    ["B-BBEE Level 3", "ISO 9001"],
    3.7,
    80,
    76,
    72,
    "watch",
    3,
    "ZAR",
    2_000,
    "Cape Town port specialists. Cheaper on sea freight, thin on inland legs.",
  ),
];
